# Welcome to Jekyll with Jekyller CMS services integrated!
#
# This comes from the Jekyller webclient starter site at:
# https://github.com/kusog/jekyller-webclient
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jekyller Content Management System
email: admin@jekyller.com
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://jekyller.com/" # the base hostname & protocol for your site, e.g. http://example.com
realBaseUrl: "/"

# Jekyller API urls from Jekyller serverless aws lambdas.  You must deploy
# Jekyller services on amazon aws. 
# https://github.com/kusog/jekyller-services
createPostUrl: https://90pwj9lg4b.execute-api.us-east-1.amazonaws.com/dev/createPost
updateContentUrl: https://90pwj9lg4b.execute-api.us-east-1.amazonaws.com/dev/updateContent
loginUrl: https://32svenpni2.execute-api.us-east-1.amazonaws.com/dev/login
  
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compressed
  load_paths:
      - css
      - node_modules

collections:
  docs:
    output: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
